language: c
dist: trusty
sudo: required

cache:
  - apt
  - npm
  directories:
  - .spago
  - output
  - node_modules

before_install:
  - sudo apt-get install -y npm
  - npm i -g npm
  - npm -v
  - npm install -g spago parcel purescript purescript-psa

script:
  - make clean package

