language: c
dist: trusty
sudo: required

cache:
  npm: true
  directories:
  - .spago
  - output
  - node_modules

before_install:
  - npm -v
  - export PATH="node_modules/.bin:$PATH"
  - which parcel && which spago && which purs && which psa || npm install parcel@1.12.4 spago@0.14.0 purescript-psa@0.7.3 purescript@0.13.6

script:
  - make clean package
