language: c
dist: trusty
sudo: required

cache:
  apt: true
  npm: true
  directories:
  - .spago
  - output
  - node_modules

before_install:
  - sudo apt-get install -y npm
  - npm i -g npm@6.14.1
  - npm -v
  - npm install -g spago parcel purescript purescript-psa

script:
  - which npm
  - make clean package

