language: c
dist: trusty
sudo: required

cache:
  directories:
  - .spago
  - output

before_install:
  - sudo apt-get install -y npm
  - npm -v
  - npm install -g spago parcel purescript purescript-psa

script:
  - make clean package

